name: JPackage Macos

on:
  release:
    types: [ released, prereleased ]

jobs:
  gradle:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: jpackage
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - uses: softprops/action-gh-release@v1
        with:
          files: build/jpackage/*.pkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
